### ISSUE TITLE
Icinga2 API access failing on check

### ISSUE THREAD

**Issue by leprasmurf** [bashgeek/icinga-multi-status#6]
When attempting to add my Icinga2 instance for API parsing the extension gets stuck on "checking".  I've opened the console and found the last URL loaded by the extension and the preview reports "Failed to load response data".  I copy the URL and open it in a tab, and a very large amount of data is loaded (32.9MB).  I'm guessing that either the extension or chrome have hit some transfer limit and this has caught the extension in a loop.

When trying to add the server to the config I am finding that I have to keep re-entering the same data because the server is not saved until a successful connection.  This is a bit annoying and repetitive.  It would be really nice if the values I've entered were saved and I could go back and modify/update them as needed.

When first installed the extension reports that everything is good, which is a bit misleading when no servers are defined.  Perhaps a link to the configuration page if no servers have been added yet?

Thanks!
Tim

**Comment by bashgeek** [comment]
Hi Tim,
thanks for your post. I just pushed out a new version containing a larger timeout (half your setup refresh-rate to be exact) instead of the fixed 10 seconds from previous versions. This, hopefully, should solve your problem with your large Icinga setup, assuming a high refresh-rate. 

I also added an information text and link to the options, when there is no instance added yet.

Feel free to report any further problems.
